services:
  ros2_app:
    image: luminousllama/stereo-camera:latest
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      - DISPLAY=${DISPLAY}
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1001:/run/user/1001
      - /dev/bus/usb:/dev/bus/usb
      - /dev/:/dev/
      - ./src/depth_estimation_node:/ros2_ws/src/depth_estimation_node
      - ./images:/ros2_ws/src/images
      - ./bags:/ros2_ws/bags
    ipc: host
    network_mode: host
